version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/app/data
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_PATH=/app/data/db.sqlite
      - BCRYPT_SALT_ROUNDS=10